# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest # self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo Hello, world!
          ls /

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |

          echo "Status before"
          ls -la
          git status
          git branch
          
          echo "Status after"
          if [ ! -d "./bin" ]; then mkdir ./bin ; fi
          
          echo "111"
          echo "try 1 ${{ github.GITHUB_RUN_NUMBER }}"
          echo "try 2 ${{ env.GITHUB_RUN_NUMBER }}"
          echo "try 2 ${env.GITHUB_RUN_NUMBER}"
          echo "hello world3 ${{ github.GITHUB_RUN_NUMBER }}" >> ./bin/app.js
          echo "222"
          ls -la
          git status
          git branch
          echo "333"
          
          echo "Adding new bin content then push"
          git add ./bin
          echo "444"         
          git config --global user.email "dudi938@gmail.com"
          git config --global user.name "David G"
          
          git commit -m "update new bin"
          echo "555"
      - name: Push changes   
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: main
